### ISSUE TITLE
NPE PlaceholderDependencyManager.getReplacementText and other issues with running examples from Stepic preview

### ISSUE THREAD

**Issue by mserge** [BruceEckel/AtomicKotlinExamples#14]
Environment:
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.3283.2, built on October 2, 2018
IntelliJ IDEA EAP User
Expiration date: November 1, 2018
JRE: 1.8.0_152-release-1343-b3 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin: EduTools v2.0-2018.2-906
Kotlin dependency set     ext.kotlin_version = '1.2.51' (as 1.3.0 no yet publically available to gradle-plugin)
Gradle set into 4.7 as 4.10 generate cannot run command-line task with issue (idea.log):

> 2018-10-08 22:01:02,824 [  70545]   WARN - ecker.gradle.GradleCommandLine - #educational: executing :Programming_Basics-String_Templates-Exercise_2:test fails: 
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings

When opening the \AtomicKotlin\Programming Basics\String Templates\Exercise 1\src\Task.kt from either project view or learning view it got exception:

> kotlin.KotlinNullPointerException
> 	at com.jetbrains.edu.learning.placeholderDependencies.PlaceholderDependencyManager.getReplacementText(PlaceholderDependencyManager.kt:81)
> 	at com.jetbrains.edu.learning.placeholderDependencies.PlaceholderDependencyManager.updateDependentPlaceholders(PlaceholderDependencyManager.kt:51)
> 	at com.jetbrains.edu.learning.editor.EduEditorFactoryListener.editorCreated(EduEditorFactoryListener.java:102)
> 	at sun.reflect.GeneratedMethodAccessor335.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:133)
> 	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:25)
> 	at com.intellij.util.EventDispatcher$3.invoke(EventDispatcher.java:96)
> 	at com.sun.proxy.$Proxy43.editorCreated(Unknown Source)
> 	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:208)
> 	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:160)
> 	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.createEditor(TextEditorComponent.java:144)
> 	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:81)
> 	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:96)
> 	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:89)
> 	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:74)
> 	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:56)
> 	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:45)
> 	at com.jetbrains.edu.learning.editor.EduEditor.<init>(EduEditor.java:27)
> 	at com.jetbrains.edu.learning.editor.EduFileEditorProvider.createEditor(EduFileEditorProvider.java:29)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$8(FileEditorManagerImpl.java:858)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:672)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:685)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:963)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:783)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:765)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:765)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:696)
> 	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:145)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditor$10(FileEditorManagerImpl.java:1121)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
> 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1119)
> 	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:152)
> 	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:138)
> 	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:134)
> 	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:117)
> 	at com.intellij.psi.impl.source.PsiFileImpl.navigate(PsiFileImpl.java:892)
> 	at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$1(NavigationUtil.java:176)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
> 	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:169)
> 	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:228)
> 	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:238)
> 	at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:133)
> 	at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:119)
> 	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:74)
> 	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:58)
> 	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:51)
> 	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:19)
> 	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:128)
> 	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:120)
> 	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
> 	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> 	at java.awt.Component.processMouseEvent(Component.java:6548)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
> 	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
> 	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
> 	at java.awt.Component.processEvent(Component.java:6313)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4903)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4725)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4725)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

@svtk

**Comment by mserge** [comment]
Found in EduTools Youtrack also, but I suppose it's related to AtomicKotlin course files https://youtrack.jetbrains.com/issue/EDU-1681
